version: '3'
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        ROOT: /app
    container_name: 'app'
    command: make run
    environment:
      FIREBASE_AUTH_CREDENTIALS: './api/credentials.json'
      GO_PORT: '${GO_PORT}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_PORT: '${MYSQL_PORT}'
    volumes:
      - ./src:/app
    ports:
      - '${GO_PORT}:${GO_PORT}'
  db:
    image: mariadb:latest
    container_name: '${MYSQL_HOST}'
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    expose:
      - '${MYSQL_PORT}'

volumes:
  db-data:
